swsec_team1/__init__.py
import config
from flask import Flask, render_template
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import MetaData

naming_convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention))

migrate = Migrate()


def create_app():
    app = Flask(__name__, static_folder='static')
    app.config.from_object(config)

    # set optional bootswatch theme
    app.config['FLASK_ADMIN_SWATCH'] = 'cerulean'

    # configure session to use sys
    app.config['SESSION_PERMANENT'] = False

    # ORM
    db.init_app(app)
    if app.config['SQLALCHEMY_DATABASE_URI'].startswith("sqlite"):
        migrate.init_app(app, db, render_as_batch=True)
    else:
        migrate.init_app(app, db)

    from . import Models

    from flask import Blueprint
    from .views import main_views, menu_views, review_views, auth_views

    app.register_blueprint(main_views.bp)
    app.register_blueprint(menu_views.bp)
    app.register_blueprint(review_views.bp)
    app.register_blueprint(auth_views.bp)

    @app.errorhandler(404)
    def not_found_error(error):
        return render_template('404.html')

    return app


app = create_app()

swsec_team1/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from .. import db
from ..Forms import UserCreateForm, UserLoginForm
from ..Models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/register/', methods=('GET', 'POST'))
def register():
    if not session.get('logged_in'):
        form = UserCreateForm()
        if request.method == 'POST' and form.validate_on_submit():
            user = User.query.filter_by(username=form.username.data).first()
            email = User.query.filter_by(email=form.email.data).first()
            if not user:
                user = User(username=form.username.data, password=generate_password_hash(form.password1.data),
                            email=form.email.data, access=form.access.data)
                db.session.add(user)
                db.session.commit()
                return redirect(url_for('auth.login'))
            else:
                if email:
                    flash('Email Already Exists')
                elif user:
                    flash('User Already Exists')
                else:
                    flash('User and Email Already Exist')
    else:
        flash('Already logged in')
        return redirect(url_for('main.index'))
    return render_template('auth/register.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    if not session.get('logged_in'):
        form = UserLoginForm()
        if request.method == 'POST' and form.validate_on_submit():
            error = None
            user = User.query.filter_by(username=form.username.data).first()
            if not user:
                error = 'Username {} does not exist.'.format(form.username.data)
            elif not check_password_hash(user.password, form.password.data):
                error = 'Incorrect password.'
            if error is None:
                session.clear()
                session['user_id'] = user.id
                session['logged_in'] = True
                return redirect(url_for('main.index'))
            flash(error)
    else:
        flash("Already logged in")
        return redirect(request.url)
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)
        session['logged_in'] = True


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

swsec_team1/views/main_views.py
from flask import Blueprint, render_template, g, redirect, url_for
from ..Models import Menu

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/')
def index():
    if g.user is None:  # no login
        return redirect(url_for('menu._list'))
    elif g.user.access == 0:    # operator
        return redirect(url_for('menu.sales'))
    else:   # customer
        return redirect(url_for('menu._list'))


@bp.route('menu_list/')
def menus_list():
    menu_list = Menu.query.order_by(Menu.uploaded_date.desc())
    return render_template('menu/menu_list.html', menu_list=menu_list)

swsec_team1/views/menu_views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, g, session
from swsec_team1.Forms import MenuUploadForm
from swsec_team1.Models import Menu
from swsec_team1 import db
from werkzeug.utils import secure_filename, redirect
from Menu_func import allowed_file, get_extension, calc, get_suggestion
from datetime import datetime
import os

bp = Blueprint('menu', __name__, url_prefix='/menu')
temp_db = 'swsec_team1/static/uploads'


@bp.route('/upload', methods=('GET', 'POST'))
def upload():
    form = MenuUploadForm()
    if request.method == 'POST' and g.user.access == 0:
        menu = Menu(name=form.name.data, price=form.price.data,
                    ingredients=form.ingredients.data, uploaded_date=datetime.now(), user=g.user)
        db.session.add(menu)
        db.session.commit()
        image = request.files['figure']
        if image and allowed_file(image.filename):
            ext = get_extension(image.filename)
            filename = secure_filename(form.name.data + ext)
            image.save(os.path.join(temp_db, filename))
        flash("Successfully Uploaded!")
        return redirect(url_for('menu.detail', menu_id=menu.id))
    elif g.user.access == 1:
        flash("CANNOT ACCESS")
        return redirect(url_for('menu._list'))
    return render_template('menu/menu_upload.html', form=form)


@bp.route('/menu_list', methods=['GET'])
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    menu_list = Menu.query.order_by(Menu.uploaded_date.desc())

    if kw:
        search = '%%{}%%'.format(kw)
        menu_list = menu_list.filter(Menu.name.ilike(search)
                                     | Menu.ingredients.ilike(search)).distinct()

    menu_list = menu_list.paginate(page, per_page=10)

    return render_template('menu/menu_list.html', menu_list=menu_list, page=page, kw=kw)


@bp.route('/detail/<int:menu_id>')
def detail(menu_id):
    menu = Menu.query.get_or_404(menu_id)
    menu.uploaded_date = menu.uploaded_date  # 날짜 표현 수정 필요. SQL ERROR 발생

    rating = calc(menu)[0]
    sales = calc(menu)[1]

    menu.rate = rating
    menu.sales = sales

    db.session.add(menu)
    db.session.commit()

    suggestion = get_suggestion(menu)

    filenames = [(menu.name + ".jpg"), (menu.name + ".png")]
    file_list = os.listdir(temp_db)
    file = ''
    for i in file_list:
        for n in filenames:
            if i == n:
                file = i
                break

    figure = 'uploads/' + file

    return render_template('menu/menu_detail.html', menu=menu, rating=rating, figure=figure, suggestion=suggestion)


@bp.route('/sales')
def sales():
    menus = list()
    total_sales = 0
    total_reviews = 0
    earnings = 0

    for m in db.session.query(Menu).all():
        menus.append([m, get_suggestion(m)])
        total_sales += int(m.sales)
        total_reviews += int(len(m.review_set))
        earnings += total_sales * int(m.price)

    return render_template('menu/sales.html', menus=menus, total_sales=total_sales, total_reviews=total_reviews,
                           earnings=earnings)

swsec_team1/views/review_views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from swsec_team1.Forms import MenuUploadForm
from swsec_team1.Models import Review, Menu
from swsec_team1 import db
from werkzeug.utils import secure_filename, redirect
from datetime import datetime
import os

bp = Blueprint('review', __name__, url_prefix='/review')


@bp.route('/create/<int:menu_id>', methods=('POST',))
def create(menu_id):
    menu = Menu.query.get_or_404(menu_id)
    rating = request.form['rating']
    sales = request.form['sales']
    review = Review(rating=rating, sales=sales, create_date=datetime.now())
    menu.review_set.append(review)
    db.session.commit()
    total_sales = 0
    total_sales += int(sales)
    return redirect(url_for('menu.detail', menu_id=menu_id))

swsec_team1/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link href="{{ url_for('static', filename='img/logo/logo.png') }}" rel="icon">
  <title>TEAM1</title>
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static', filename='css/ruang-admin.min.css') }}" rel="stylesheet">
</head>

<body id="page-top">
  <div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url_for('main.index') }}">
        <div class="sidebar-brand-icon">
          <img src="{{ url_for('static', filename='img/logo/logo2.png') }}">
        </div>
        <div class="sidebar-brand-text mx-3">TEAM1</div>
      </a>
      <hr class="sidebar-divider my-0">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main.index') }}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>
      <hr class="sidebar-divider">
      <div class="sidebar-heading">
        Features
      </div>
        {% if g.user.access == 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.index') }}">
          <i class="fab fa-fw fa-wpforms"></i>
          <span>Sales</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('menu._list') }}">
          <i class="fas fa-fw fa-table"></i>
          <span>Manage - Menu</span>
        </a>
      </li>
        {% endif %}
        {% if g.user.access != 0 %}
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('menu._list') }}">
          <i class="fas fa-fw fa-table"></i>
          <span>Menu</span>
        </a>
      </li>
        {% endif %}
    </ul>
    <!-- Sidebar -->
    <div id="content-wrapper" class="d-flex flex-column">
      <div id="content">
      <!-- TopBar -->
            <div class="topbar-divider d-none d-sm-block"></div>
              <nav class="navbar navbar-expand navbar-light bg-navbar topbar mb-4 static-top">
                  <button id="sidebarToggleTop" class="btn btn-link rounded-circle mr-3">
                      <i class="fa fa-bars"></i>
                  </button>
                  <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown no-arrow">
                  <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-search fa-fw"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                       aria-labelledby="searchDropdown" >
                      <form class="navbar-search" method="get" action="{{ url_for('menu._list') }}">
                          <div class="input-group">
                              <input type="text" class="form-control bg-light border-1 small" placeholder="What do you want to look for?"
                                     id="kw" name="kw" aria-label="Search" aria-describedby="basic-addon2" style="border-color: #3f51b5;" value="{{ kw or '' }}">
                              <div class="input-group-append">
                                  <button class="btn btn-primary" type="submit">
                                      <i class="fas fa-search fa-sm"></i>
                                  </button>
                              </div>
                          </div>
                      </form>
                  </div>
          </li>
                      <div class="topbar-divider d-none d-sm-block"></div>
          {% if g.user %}
            <li class="nav-item dropdown no-arrow">

              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <img class="img-profile rounded-circle" src="{{ url_for('static', filename='img/boy.png') }}" style="max-width: 60px">
                <span class="ml-2 d-none d-lg-inline text-white small">{{ g.user.username }}</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
                {% else %}
                    <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="ml-2 d-none d-lg-inline text-white small">Log in / Register</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('auth.login') }}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Log In
                </a>
                  <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('auth.register') }}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Register
                </a>
              </div>
                {% endif %}
            </li>
          </ul>
        </nav>
        <!-- Topbar -->
        <!-- Container Fluid-->
        <div class="container-fluid" id="container-wrapper">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{% block title %}{% endblock %}</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
              {% block category %}{% endblock %}
              <li class="breadcrumb-item active" aria-current="page">{% block current_page %}{% endblock %}</li>
            </ol>
          </div>

            {% block contents %}
            {% endblock %}
        </div>
      </div>
              <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>copyright &copy; <script> document.write(new Date().getFullYear()); </script> - developed by
              <b>SWSECURITY - TEAM01</b>
            </span>
          </div>
        </div>
      </footer>
      <!-- Footer -->
        <!---Container Fluid-->
      </div>
    </div>

  <!-- Scroll to top -->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/ruang-admin.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/chart.js/Chart.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/demo/chart-area-demo.js') }}"></script>


</body>

</html>

swsec_team1/templates/menu/menu_detail.html
{% extends 'base.html' %}

{% block title %}
    Menu
{% endblock %}

{% block category %}
    <li class="breadcrumb-item">Menu</li>
{% endblock %}

{% block current_page %}
    {{ menu.name }}
{% endblock %}

{% block contents %}
   <div style="float: left;"><h1><strong>{{ menu.name }}</strong></h1></div>
    <br><br><br>
    <p style="float: left;">last updated: {{ menu.uploaded_date }}</p>

    {% if g.user.id == 1 %}
    <p style="float: right;">SUGGESTION : &nbsp;&nbsp;
    {% if suggestion == None %}<span class="badge badge-warning" style="float:right; margin-right: 3%; margin-top: -13%">LOW SALES</span>{% endif %}
    {% if suggestion == 0 %}<span class="badge badge-danger" style="float:right; margin-right: 3%; margin-top: -13%">CHANGE</span>{% endif %}
    {% if suggestion == 1 %}<span class="badge badge-info" style="float:right; margin-right: 3%; margin-top: -13%">GOOD</span>{% endif %}
    {% if suggestion == 2 %}<span class="badge badge-success" style="float:right; margin-right: 3%; margin-top: -13%">BEST</span>{% endif %}
    </p>
    {% endif %}
    <br><br><br>


    <!-- Introduction of database -->
    <div class="col-lg-12">
    <div class="card mb-4">
    <div class="card-body">
{#        <div style="display: inline-block;">#}
{#            <img src="{{ url_for('static', filename=figure) }}" style="max-width:50%; max-height: 50%; vertical-align: middle;">#}
{#        </div>#}
        <div class="card-group">
        <div class="col-xl-3 col-md-6 mb-4">
              <div class="card h-100">
                <div class="card-body">
                  <div class="row align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-uppercase mb-1">Ingredients</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{ menu.ingredients }}</div>
                    </div>
                  </div>
                </div>
              </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
              <div class="card h-100">
                <div class="card-body">
                  <div class="row align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-uppercase mb-1">Reviews</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">{{ menu.review_set|length }}</div>
                    </div>
                  </div>
                </div>
              </div>
        </div>

            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card h-100">
                <div class="card-body">
                  <div class="row align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-uppercase mb-1">Rating</div>
                        {% if menu.review_set|length != 0 %}
                      <div class="h5 mb-0 font-weight-bold text-gray-800">★ {{ rating }} <hr>{{ menu.sales }} orders</div>
                        {% endif %}
                        {% if menu.review_set|length == 0 %}
                      <div class="h5 mb-0 font-weight-bold text-gray-800">There is no review</div>
                        {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card h-100">
                <div class="card-body">
                  <div class="row align-items-center">
                    <div class="col mr-2" style="overflow: hidden">
                        <img src="{{ url_for('static', filename=figure) }}"
                             style="width: 100%; height: auto; object-fit: cover;">
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>

    <br><br><br>
        {% if g.user.access == 1 %}
            <hr>
        <div>
            <form action="{{ url_for('review.create', menu_id=menu.id) }}" method="post">
                <div class="form-group" style="width: fit-content;">
                      <label for="rating">Select rating of {{ menu.name }}</label>
                      <select class="form-control" id="rating" name="rating">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                      </select>
                </div>
                <div class="form-group" style="width: fit-content;">
                      <label for="sales">Please enter your purchase volume</label>
                      <select class="form-control" id="sales" name="sales">
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option>6</option>
                        <option>7</option>
                        <option>8</option>
                        <option>9</option>
                        <option>10</option>
                      </select>
                </div>
                <button type="submit" class="btn btn-primary" value="Upload">Submit</button>
            </form>
        </div>
        {% endif %}
    </div>

    </div>


    </div>

{% endblock %}

<!-- Page level plugins -->
<script src="{{ url_for('static', filename='vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

swsec_team1/templates/menu/menu_list.html
{% extends 'base.html' %}

{% block title %}
    Menu
{% endblock %}

{% block category %}
    <li class="breadcrumb-item">Menu</li>
{% endblock %}

{% block current_page %}
    List
{% endblock %}

{% block contents %}
<div class="col-lg-12">
      <div class="card mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Menu List</h6>
        </div>
        <div class="table-responsive p-3">
          <table class="table align-items-center table-flush table-hover" id="dataTableHover">
            <thead class="thead-light">
              <tr>
                  <th>No</th>
                  <th>Name</th>
                  <th>Ingredients</th>
                  <th>Price</th>
                  <th>Rating</th>
              </tr>
            </thead>
            <tbody>
            {% if menu_list != None %}
            {% for menu in menu_list.items %}
              <tr>
                  <td>{{ menu_list.total - ((menu_list.page-1)*menu_list.per_page) - loop.index0 }}</td>
                  <td><a href="{{ url_for('menu.detail', menu_id=menu.id) }}">{{ menu.name }}</a></td>
                  <td>{{ menu.ingredients }}</td>
                  <td>{{ menu.price }}</td>
                  {% if menu.rate != 0 %}
                  <td>{{ menu.rate }}</td>
                  {% endif %}
                  {% if menu.rate == 0 %}
                  <td>No Reviews</td>
                  {% endif %}
              </tr>
            {% endfor %}
            {% endif %}
            {% if menu_list == None %}
            <p>There is no menu</p>
            {% endif %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <ul class="pagination justify-content-center">
    <!-- previous page -->
    {% if menu_list.has_prev %}
        <li class="page-item">
        <a class="page-link" href="?page={{ menu_list.prev_num }}">Previous</a>
        </li>
    {% else %}
        <li class="page-item">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Previous</a>
        </li>
    {% endif %}

    <!-- current page -->
    {% for page_num in menu_list.iter_pages() %}
        {% if page_num %}
            {% if page_num != menu_list.page %}
                <li class="page-item">
                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
            {% else %}
                <li class="page-item" aria-current="page">
                <a class="page-link" href="#">{{ page_num }}</a>
                </li>
            {% endif %}
        {% else %}
            <li class="disabled">
            <a class="page-link" href="#">...</a>
            </li>
        {% endif %}
    {% endfor %}

    <!-- next page -->
    {% if menu_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ menu_list.next_num }}">Next</a>
        </li>
    {% else %}
        <li class="page-item">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
        </li>
    {% endif %}
    </ul>
    {% if g.user.access == 0 %}
    <a href="{{ url_for('menu.upload') }}" class="btn btn-sm btn-primary">Upload Your Menu!</a>
    {% endif %}
{% endblock %}

  <!-- Page level plugins -->
  <script src="{{ url_for('static', filename='vendor/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

  <!-- Page level custom scripts -->
  <script>
    $(document).ready(function () {
      $('#dataTable').DataTable(); // ID From dataTable
      $('#dataTableHover').DataTable(); // ID From dataTable with Hover
    });
  </script>

    <script type="text/javascript">
    $(document).ready(function(){
        $(".page-link").on('click', function() {
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
        });
        $("btn_search").on('click', function() {
            $("#search_bar").val($(".search_bar").val());
            $("#page").val(1);
            $("#searchForm").submit();
        });
    });
    </script>

swsec_team1/templates/menu/menu_upload.html
{% extends 'base.html' %}

{% block title %}
    Menu
{% endblock %}

{% block category %}
    <li class="breadcrumb-item">Menu</li>
{% endblock %}

{% block current_page %}
    Upload
{% endblock %}

{% block contents %}
    <div class="card mb-3">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">MENU</h6>
        </div>
        <div class="card-body">
            <p><b>Upload your menu!</b></p><br>
            <form action="{{ url_for('menu.upload') }}" method="post" enctype="multipart/form-data">
                {% for field, errors in form.errors.items() %}
                    <div class="alert alert-danger" role="alert">
                        <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
                    </div>
                {% endfor %}
                <div class="form-group">
                    {{ form.name.label }}
                    {{ form.name(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.price.label }}
                    {{ form.price(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.ingredients.label }}
                    {{ form.ingredients(class='form-control') }}
                </div>
                <div class="form-group">
                    <label for="customFile">Image</label>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="figure" name="figure">
                        <label class="custom-file-label" for="figure" id="figureName"></label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary" value="Upload">Submit</button>
            </form>
        </div>
      </div>

{% endblock %}